---
ID: "e5a17a8e-427a-4fb3-a574-56f41a3681d7"
Parent: "a3433efd-6d7f-457e-94e4-9f7559b5bd06"
Template: "a3433efd-6d7f-457e-94e4-9f7559b5bd06"
Path: /sitecore/templates/Foundation/SF/CodeEditor/Item Templates/MediaResource/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20140510T202117
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
